"use client";

import { useState, useCallback } from "react";
import { trackUsage, trackDownload } from "@/lib/analytics";

/** GST rate slabs available in India */
const GST_RATES = [0, 5, 12, 18, 28] as const;

/** Calculation mode: exclusive adds GST, inclusive extracts GST */
type CalcMode = "exclusive" | "inclusive";

/** Supply type determines CGST+SGST vs IGST */
type SupplyType = "intra" | "inter";

/** Result of a GST computation */
interface GstResult {
  baseAmount: number;
  gstAmount: number;
  cgst: number;
  sgst: number;
  igst: number;
  totalAmount: number;
  rate: number;
  supplyType: SupplyType;
}

/** Formats a number as Indian rupee currency */
function formatINR(value: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
}

/**
 * GST Calculator tool: calculate CGST, SGST, IGST breakup for Indian invoices.
 */
export default function GstCalculator() {
  const [amount, setAmount] = useState("");
  const [rate, setRate] = useState<number>(18);
  const [mode, setMode] = useState<CalcMode>("exclusive");
  const [supplyType, setSupplyType] = useState<SupplyType>("intra");
  const [result, setResult] = useState<GstResult | null>(null);
  const [error, setError] = useState("");

  const handleCalculate = useCallback(() => {
    setError("");
    setResult(null);

    const numAmount = parseFloat(amount);
    if (isNaN(numAmount) || numAmount <= 0) {
      setError("Please enter a valid positive amount.");
      return;
    }

    let baseAmount: number;
    let gstAmount: number;
    let totalAmount: number;

    if (mode === "exclusive") {
      baseAmount = numAmount;
      gstAmount = numAmount * (rate / 100);
      totalAmount = baseAmount + gstAmount;
    } else {
      totalAmount = numAmount;
      baseAmount = numAmount / (1 + rate / 100);
      gstAmount = totalAmount - baseAmount;
    }

    const cgst = supplyType === "intra" ? gstAmount / 2 : 0;
    const sgst = supplyType === "intra" ? gstAmount / 2 : 0;
    const igst = supplyType === "inter" ? gstAmount : 0;

    setResult({
      baseAmount,
      gstAmount,
      cgst,
      sgst,
      igst,
      totalAmount,
      rate,
      supplyType,
    });

    trackUsage("gst-calculator", "GST Calculator");
  }, [amount, rate, mode, supplyType]);

  const handleDownload = useCallback(() => {
    if (!result) return;

    const lines = [
      "GST Calculation Summary",
      "========================",
      `Date: ${new Date().toLocaleDateString("en-IN")}`,
      "",
      `Mode: ${mode === "exclusive" ? "Add GST to amount" : "Extract GST from amount"}`,
      `Supply Type: ${result.supplyType === "intra" ? "Intra-state (CGST + SGST)" : "Inter-state (IGST)"}`,
      `GST Rate: ${result.rate}%`,
      "",
      `Base Amount: ${formatINR(result.baseAmount)}`,
      `GST Amount: ${formatINR(result.gstAmount)}`,
    ];

    if (result.supplyType === "intra") {
      lines.push(`  CGST (${result.rate / 2}%): ${formatINR(result.cgst)}`);
      lines.push(`  SGST (${result.rate / 2}%): ${formatINR(result.sgst)}`);
    } else {
      lines.push(`  IGST (${result.rate}%): ${formatINR(result.igst)}`);
    }

    lines.push("");
    lines.push(`Total Amount: ${formatINR(result.totalAmount)}`);
    lines.push("");
    lines.push("---");
    lines.push("Generated by kit.brtneura.com/tools/gst-calculator");
    lines.push("Disclaimer: This is a convenience tool. Always verify with a qualified CA.");

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `gst-summary-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    trackDownload("gst-calculator");
  }, [result, mode]);

  return (
    <div className="space-y-6">
      {/* How to use guide */}
      <details className="group rounded-lg border border-white/10 bg-white/[0.03]">
        <summary className="flex cursor-pointer items-center justify-between px-4 py-3 text-sm font-medium text-zinc-300">
          How to use this tool
          <span className="text-zinc-600 transition-transform group-open:rotate-180">&#9660;</span>
        </summary>
        <div className="border-t border-white/10 px-4 py-3 text-xs leading-relaxed text-zinc-400 space-y-2">
          <p><strong className="text-zinc-300">Step 1:</strong> Enter the amount in rupees.</p>
          <p><strong className="text-zinc-300">Step 2:</strong> Select the GST rate slab — 0%, 5%, 12%, 18%, or 28%.</p>
          <p><strong className="text-zinc-300">Step 3:</strong> Choose calculation mode — <strong className="text-zinc-300">Add GST</strong> (for exclusive pricing) or <strong className="text-zinc-300">Extract GST</strong> (to find GST included in an MRP).</p>
          <p><strong className="text-zinc-300">Step 4:</strong> Select supply type — <strong className="text-zinc-300">Intra-state</strong> (same state, splits into CGST + SGST) or <strong className="text-zinc-300">Inter-state</strong> (different state, shows IGST).</p>
          <p><strong className="text-zinc-300">Step 5:</strong> Click <strong className="text-indigo-400">Calculate GST</strong> to see the breakup.</p>
          <p><strong className="text-zinc-300">Step 6:</strong> Optionally <strong className="text-emerald-400">Download Summary</strong> as a .txt file for your records.</p>
          <p className="text-zinc-500 pt-1">Supports all Indian GST slabs. Always verify with a qualified CA for invoicing.</p>
        </div>
      </details>

      {/* Amount input */}
      <div>
        <label className="mb-2 block text-sm font-medium text-zinc-300">
          Amount
        </label>
        <div className="relative">
          <span className="absolute left-4 top-1/2 -translate-y-1/2 text-sm text-zinc-500">
            ₹
          </span>
          <input
            type="number"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
            placeholder="10000"
            min="0"
            step="0.01"
            className="w-full rounded-lg border border-white/10 bg-white/[0.05] py-3 pl-9 pr-4 text-sm text-white placeholder-zinc-600 outline-none transition-colors focus:border-indigo-500/50 focus:ring-1 focus:ring-indigo-500/30"
          />
        </div>
      </div>

      {/* GST Rate selector */}
      <div>
        <label className="mb-2 block text-sm font-medium text-zinc-300">
          GST Rate
        </label>
        <div className="flex flex-wrap gap-2">
          {GST_RATES.map((r) => (
            <button
              key={r}
              onClick={() => setRate(r)}
              className={`rounded-full px-4 py-1.5 text-sm font-medium transition-colors ${
                rate === r
                  ? "bg-indigo-600 text-white"
                  : "bg-white/10 text-zinc-400 hover:bg-white/15 hover:text-white"
              }`}
            >
              {r}%
            </button>
          ))}
        </div>
      </div>

      {/* Calculation mode toggle */}
      <div>
        <label className="mb-2 block text-sm font-medium text-zinc-300">
          Calculation Mode
        </label>
        <div className="flex gap-2">
          <button
            onClick={() => setMode("exclusive")}
            className={`flex-1 rounded-lg px-4 py-2.5 text-sm font-medium transition-colors ${
              mode === "exclusive"
                ? "bg-indigo-600/20 text-indigo-400 border border-indigo-500/40"
                : "bg-white/[0.05] text-zinc-400 border border-white/10 hover:bg-white/10"
            }`}
          >
            Add GST to amount
          </button>
          <button
            onClick={() => setMode("inclusive")}
            className={`flex-1 rounded-lg px-4 py-2.5 text-sm font-medium transition-colors ${
              mode === "inclusive"
                ? "bg-indigo-600/20 text-indigo-400 border border-indigo-500/40"
                : "bg-white/[0.05] text-zinc-400 border border-white/10 hover:bg-white/10"
            }`}
          >
            Extract GST from amount
          </button>
        </div>
      </div>

      {/* Supply type toggle */}
      <div>
        <label className="mb-2 block text-sm font-medium text-zinc-300">
          Supply Type
        </label>
        <div className="flex gap-2">
          <button
            onClick={() => setSupplyType("intra")}
            className={`flex-1 rounded-lg px-4 py-2.5 text-sm font-medium transition-colors ${
              supplyType === "intra"
                ? "bg-indigo-600/20 text-indigo-400 border border-indigo-500/40"
                : "bg-white/[0.05] text-zinc-400 border border-white/10 hover:bg-white/10"
            }`}
          >
            Intra-state (CGST + SGST)
          </button>
          <button
            onClick={() => setSupplyType("inter")}
            className={`flex-1 rounded-lg px-4 py-2.5 text-sm font-medium transition-colors ${
              supplyType === "inter"
                ? "bg-indigo-600/20 text-indigo-400 border border-indigo-500/40"
                : "bg-white/[0.05] text-zinc-400 border border-white/10 hover:bg-white/10"
            }`}
          >
            Inter-state (IGST)
          </button>
        </div>
      </div>

      {/* Calculate button */}
      <button
        onClick={handleCalculate}
        disabled={!amount.trim()}
        className="w-full rounded-lg bg-gradient-to-r from-indigo-600 to-purple-600 px-5 py-3 text-sm font-semibold text-white transition-opacity hover:opacity-90 disabled:opacity-40 disabled:cursor-not-allowed"
      >
        Calculate GST
      </button>

      {/* Error */}
      {error && (
        <div className="rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-400">
          {error}
        </div>
      )}

      {/* Results */}
      {result && (
        <div className="space-y-4">
          <div className="rounded-lg border border-white/10 bg-white/[0.03] p-5">
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
              {/* Base Amount */}
              <div className="rounded-lg bg-white/[0.05] p-4">
                <p className="text-xs text-zinc-500">Base Amount</p>
                <p className="mt-1 text-lg font-semibold text-white">
                  {formatINR(result.baseAmount)}
                </p>
              </div>

              {/* GST Amount */}
              <div className="rounded-lg bg-amber-500/10 border border-amber-500/20 p-4">
                <p className="text-xs text-amber-400">GST Amount ({result.rate}%)</p>
                <p className="mt-1 text-lg font-semibold text-amber-300">
                  {formatINR(result.gstAmount)}
                </p>
              </div>

              {/* Tax breakup */}
              {result.supplyType === "intra" ? (
                <>
                  <div className="rounded-lg bg-white/[0.05] p-4">
                    <p className="text-xs text-zinc-500">CGST ({result.rate / 2}%)</p>
                    <p className="mt-1 text-base font-medium text-white">
                      {formatINR(result.cgst)}
                    </p>
                  </div>
                  <div className="rounded-lg bg-white/[0.05] p-4">
                    <p className="text-xs text-zinc-500">SGST ({result.rate / 2}%)</p>
                    <p className="mt-1 text-base font-medium text-white">
                      {formatINR(result.sgst)}
                    </p>
                  </div>
                </>
              ) : (
                <div className="rounded-lg bg-white/[0.05] p-4 sm:col-span-2">
                  <p className="text-xs text-zinc-500">IGST ({result.rate}%)</p>
                  <p className="mt-1 text-base font-medium text-white">
                    {formatINR(result.igst)}
                  </p>
                </div>
              )}

              {/* Total */}
              <div className="rounded-lg bg-emerald-500/10 border border-emerald-500/20 p-4 sm:col-span-2">
                <p className="text-xs text-emerald-400">Total Amount</p>
                <p className="mt-1 text-2xl font-bold text-emerald-300">
                  {formatINR(result.totalAmount)}
                </p>
              </div>
            </div>
          </div>

          {/* Download button */}
          <button
            onClick={handleDownload}
            className="rounded-lg bg-gradient-to-r from-emerald-600 to-green-600 px-5 py-2 text-sm font-medium text-white transition-opacity hover:opacity-90"
          >
            Download Summary (.txt)
          </button>

          {/* Disclaimer */}
          <p className="text-xs text-zinc-600">
            Disclaimer: This is a convenience tool. Always verify with a qualified CA.
          </p>
        </div>
      )}
    </div>
  );
}
